services:
  app:
    image: ${REGISTRY:-localhost}/${SERVICE_NAME:-gateway}:${SERVICE_VERSION:-latest}
    container_name: ${SERVICE_NAME:-gateway}
    restart: always
    environment:
      - SERVICE_ENV=${DEPLOYMENT_ENV:-development}
      - JAVA_OPTS=-Xmx512m -Xms256m
      # Additional environment variables will be loaded from env file
    env_file:
      - ./${SERVICE_NAME:-gateway}.env
    ports:
      - "${SERVICE_PORT:-8080}:8080"
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
      # - ./config/${DEPLOYMENT_ENV:-development}/${SERVICE_NAME:-gateway}.conf:/app/config/application.conf
      - ./${SERVICE_NAME}.conf:/app/config/application.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Service-specific dependencies will be added by the deployment script
    # depends_on:
    #   - service1
    #   - service2

networks:
  app-network:
    external: true

volumes:
  app-data:
    name: ${SERVICE_NAME:-gateway}-data-${DEPLOYMENT_ENV:-development}
  app-logs:
    name: ${SERVICE_NAME:-gateway}-logs-${DEPLOYMENT_ENV:-development}
