name: Fast Unit Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew test --no-daemon --scan --parallel --max-workers=2
