name: Unit Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle # Кеширование зависимостей

      - name: Generate Gradle Wrapper
        run: |
          # Удаляем старые файлы wrapper (если есть)
          rm -f gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar

          # Генерируем новый wrapper с конкретной версией Gradle
          gradle wrapper --gradle-version 8.5 --distribution-type bin

          # Проверяем, что файлы созданы
          [ -f gradlew ] || exit 1
          [ -f gradle/wrapper/gradle-wrapper.jar ] || exit 1

          # Даем права на выполнение
          chmod +x gradlew

          # Проверяем целостность jar-файла
          unzip -t gradle/wrapper/gradle-wrapper.jar >/dev/null || exit 1

      - name: Run unit tests
        run: ./gradlew test --no-daemon --stacktrace

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test/**/*.xml
